### ISSUE TITLE
Rate function: "score" and "rank" interchangeable ?

### ISSUE THREAD

**Issue by rudnirol** [OpenDebates/openskill.py#1]
Apologies for being a noob - it seems that the score margin doesn't have any affect on how the ratings are updated and it's effectively the same as the rank option just that the higher score is better. If that is true, is there a way to consider the score margin for games where it is important?

**Comment by daegontaven** [comment]
Unfortunately the [paper](https://jmlr.csail.mit.edu/papers/volume12/weng11a/weng11a.pdf) this package implements doesn't discuss score margins. Scores are simply convenience methods that convert to ranks. A new model would have to be constructed that support score margins since ranks are a central part of all of the models used in this package.
